name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  # cash folder for pnpm_store, nextjs and playwright later on
  PW_CACHE_AFFIX: pw
  PW_CACHE_FOLDER: ~/.cache/ms-playwright

jobs:
  Build-And-Test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        node-version: ['20.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install package manager
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.6

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Setup Cache
        uses: actions/cache@v4
        id: pnpm_store_cache
        with:
          path: |
            ${{ env.PW_CACHE_FOLDER }}
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ env.PW_CACHE_AFFIX }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/.browserslistrc') }}-${{ hashFiles('**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.PW_CACHE_AFFIX }}-
            ${{ runner.os }}-${{ env.PW_CACHE_AFFIX }}-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test
        env:
          TEST_SERIAL_TIMEOUT: ${{ vars.TEST_SERIAL_TIMEOUT }}
        run: |
          pnpm test:ci
