name: Update Feature Gates
on:
  workflow_dispatch:
  schedule:
    - cron: '23 3 * * *' # Daily at 3:23 am UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install requests beautifulsoup4 solders solana

      - name: Scrape and generate features
        run: python scripts/parse_feature_gates.py

      - name: Fetch mainnet activations
        run: python scripts/fetch_mainnet_activations.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch-token: ${{ secrets.GITHUB_TOKEN }}
          sign-commits: true
          commit-message: 'Update feature gates from Agave wiki'
          title: 'Automated Feature Gates Update'
          body: 'Auto-generated PR from daily feature gates check'
          branch: 'feature-gates-update'
          base: master
          maintainer-can-modify: true
          delete-branch: true
